### ISSUE TITLE
The remote server returned an error: (422) Unprocessable Entity.Error when uploading an attatchment

### ISSUE THREAD

**Issue by bigblondeviking** [mozts2005/ZendeskApi_v2#351] opened 2018-06-29 20:47 UTC
var api = GetApiWrapper();
	var fn = Path.GetFileName(fileName); 
	var mt = MimeMapping.GetMimeMapping(fn) ?? Default_MimeType;
	var zenFile = new ZenFile
	{
	  ContentType = mt,     // {{filename}}.lic
	  FileName = fn,        // application/octet-stream
	  FileData = fileBytes  // array of bytes from file
	};
	var uploadResponse = api.Attachments.UploadAttachment(zenFile, Request_Timeout);
	return uploadResponse.Token;

> System.Net.WebException: The remote server returned an error: (422) Unprocessable Entity.Error content: {"error":"RecordInvalid","description":"Record validation errors","details":{"content_type":[{"description":"Content type cannot be blank","error":"BlankValue"}]}} 
 Resource String: uploads.json?filename=quantifi2.lic  + 
 File Name: quantifi2.lic 
 File Length: 3220
Connection: keep-alive
X-Zendesk-API-Version: v2
X-Zendesk-Application-Version: v1673.32
X-Frame-Options: SAMEORIGIN
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: X-Zendesk-API-Warn
X-Rate-Limit: 700
X-Rate-Limit-Remaining: 692
Strict-Transport-Security: max-age=31536000;
X-Zendesk-Origin-Server: app6.pod5.iad1.zdsys.com
X-Request-Id: 432ab08c1f44220a-EWR
X-Runtime: 0.248004
X-Zendesk-Request-Id: ----------
Content-Length: 163
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Date: Fri, 29 Jun 2018 19:09:49 GMT

App is .net 4.6.2, has to upgrade to get past the TLS issue.
I then upgraded the zendeskapi_v2 to the latest nuget 3.8.0 ( to see if it would fix this issue)  but it didn't

I have opened a ticket with Zendesk as well, as I don't see the failed request in the API errors.

**Comment by mozts2005** [comment] 2018-06-30 16:49
based on your error message I think you are passing a blank content type

> [{"description":"Content type cannot be blank","error":"BlankValue"}]}}

**Comment by bigblondeviking** [comment] 2018-07-02 13:00
I though so as well in the beginning, but I am setting the content type to: "application/octet-stream"

![zendeskapi_v2_upload](https://user-images.githubusercontent.com/23195258/42165024-6084a150-7dd5-11e8-8d8c-c5056e4b42d5.png)

**Comment by mozts2005** [comment] 2018-08-06 17:25
I have been unable to reproduce this issues. Can you give us a unit test that recreates the issue?

**Comment by mozts2005** [comment] 2018-10-11 13:47
No update has been given closing the issue.

**Closed by mozts2005** 2018-10-11 13:47 UTC
Labels: More Info Needed, Question, Test case needed
