### ISSUE TITLE
Retrieving macros throws exception when a macro's action contains an array value

### ISSUE THREAD

**Issue by rflorence** [mozts2005/ZendeskApi_v2#105] opened 2014-09-29 20:28 UTC
Depending on the field, some macro actions contain value properties that are strings, and some that are arrays of strings. See the "comment_value" and "notification_user" fields here: https://developer.zendesk.com/rest_api/docs/core/macros#actions

Since Action.Value is of type string, calling a get method fails when Zendesk contains one of these types of macros.

An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Error reading string. Unexpected token: StartArray. Path 'macros[1].actions[0].value', line 1, position 602.

**Comment by mozts2005** [comment] 2015-07-13 23:57
this is a duplicate of issue [#123](https://github.com/mozts2005/ZendeskApi_v2/issues/123)

I will be looking at fixing this in the next few weeks.

**Closed** 2015-07-13 23:57 UTC
Labels: duplicate
