### ISSUE TITLE
Unable to update organization after adding tag

### ISSUE THREAD

**Issue by AlexisVZ** [mozts2005/ZendeskApi_v2#109] opened 2014-10-31 11:54 UTC
Hallo,

I have code for updating an organization which runs fine. Thanks Erik !.

But now I tried to add a tag to an organization by adding the following code (VB.net), before the UpdateOrganization method:
            Dim Tag As New ZendeskApi_v2.Models.Tags.Tag
            Tag.Name = "MM"
            Organization.Tags.Add(Tag)
            api.Organizations.UpdateOrganization(Organization)

But after adding this code I receive the following error upon calling UpdateOrganization: "The remote server returned an error: (400) Bad Request."

Any help much appreciated.
Alexis

**Comment by cdwbear** [comment] 2015-02-20 23:55
I see no attached screenshot [cid:image001.png@01D01CFC.11FF3A60], but I need help with this exact problem.  Thanks.

**Comment by artfulhacker** [comment] 2015-02-21 00:04
Yea same. I figured it out, you can't reuse the Organization object response. I had to build a new one, copy the attributes over (the one I wanted to change) and send that with the request. Not impressed with this API or library after using it for several months now.

**Comment by cdwbear** [comment] 2015-02-21 00:31
Thanks for the quick response!!!  I'll try that.

I've also found that if you send the JSON over with:

 /{org id}/tags.json "{"tags":["claims","eligibility","statements"]}"

that it works just fine!  The same holds true for CustomFields as well.

None of this supported by this API wrapper of course.  I had to futz the JSON before the request was sent.

**Comment by mozts2005** [comment] 2015-07-13 23:52
Will look at ways to make this better. Please post any ideas for ways we can make this better for every one.

**Comment by StephenMP** [comment] 2015-12-01 17:54
I'm unable to reproduce this issue using the latest code.

**Comment by mozts2005** [comment] 2015-12-01 18:27
@StephenMP Would you please submit a pull request adding your code as a test case?

I am going to close this issue at this time. if more information becomes available we can reopen.

**Closed by mozts2005** 2015-12-01 18:27 UTC
Labels: More Info Needed, Up for Grabs
