### ISSUE TITLE
Inconsistant 422 Errors Unprocessable Entity - Updating Trigger

### ISSUE THREAD

**Issue by Alin-Dumitrescu** [mozts2005/ZendeskApi_v2#226] opened 2016-06-15 18:14 UTC
Hello,

I have some simple code that intends to enable an existing disabled trigger. here is the code and the error:
IndividualTriggerResponse z = zenApi.Triggers.GetTriggerById(triggerId);
z.Trigger.Active = true;
zenApi.Triggers.UpdateTrigger(zenTriggerResponse.Trigger);

The error:
System.Net.WebException was unhandled
  HResult=-2146233079
  Message=The remote server returned an error: (422) Unprocessable Entity.Error content: {"error":"RecordInvalid","description":"Record validation errors","details":{"base":[{"description":"Invalid value 'web' in 'Update via / Is not / web'"}]}} 

The trigger has a condition: Is Not updated via web Form. Somehow that makes the update unhappy. If i remove that condition, the update works.

  {
          "field": "current_via_id",
          "operator": "is_not",
          "value": "web"
        },

**Comment by mozts2005** [comment] 2016-07-13 16:58
Can you submit a test case that has this issue? I understand that sometimes the test will pass and sometimes it will fail.

**Comment by Alin-Dumitrescu** [comment] 2016-07-13 17:08
The code I put in there is 100 reproable all the time. The issue is that zendesk expects an id (eg 5) for the update method. When you get the entity, it has the value (API). So, a get, followed by update the trigger object to enable/disable ,followed by an update will fail all the time.

Thank you,
Alin

On Jul 13, 2016, at 9:58 AM, Elizabeth Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you submit a test case that has this issue? I understand that sometimes the test will pass and sometimes it will fail.

-

**Comment by mozts2005** [comment] 2016-07-13 17:11
Would you please create a test with the full workflow and submit it as a pull request and we will see about getting the issue fixed.

**Comment by Tyf0x** [comment] 2016-08-25 03:33
**# THE CAUSE**

I had a look into this and can confirm a bug (probably on zendesk side).

The trigger condition "Update Via" in the web UI corresponds to the "current_via_id" API field which expects an ID value corresponding to a [via type](https://developer.zendesk.com/rest_api/docs/core/triggers#via-types).

The problem is that when retrieving the trigger, zendesk API sends:

```JSON
"any" : [{
    "field" : "current_via_id",
    "operator" : "is_not",
    "value" : "web"
  }
]
```

which is the name value instead of the ID.

This makes the API spit an error when trying to update the Trigger on the next update.

**# TEST CODE**

1. Trigger creation:

![image](https://cloud.githubusercontent.com/assets/6980921/17955827/4eea5c04-6ac8-11e6-9abd-5525bb23e0e6.png)

2. Test code

```C#
  var myTrig = _zendeskApi.Triggers.GetTriggerById(<<insert_trigger_id>>).Trigger;
  myTrig.Active = true;
  _zendeskApi.Triggers.UpdateTrigger(myTrig);
```

**Comment by Tyf0x** [comment] 2016-09-01 01:47
Submitted a ticket to [zendesk support](https://support.zendesk.com/hc/en-us/community/posts/218130587-Triggers-endpoint-RecordInvalid-error?page=1) and awaiting and answer.

**Comment by mozts2005** [comment] 2016-09-26 16:33
Given that this is zendesk issue and the support ticket has been opened with them. I am closing this issue.

**Closed by mozts2005** 2016-09-26 16:33 UTC
Labels: bug, Test case needed
