### ISSUE TITLE
Add organization memberships to client

### ISSUE THREAD

**Issue by GothAr** [mozts2005/ZendeskApi_v2#68] opened 2014-04-02 21:12 UTC
Hello.
I cannot unassign user from organization using wrapper calls. 
From ZenDesk site you can select '-' from drop down and user will be unassigned from organization. 
But I dont know how to do this via API. When I set User's OrganizationId to null then it is not serialized to JSON and not sent to server during UpdateUser call, i.e. server thinks there were no changes to organization.

Is this functionality supported by API?

**Comment by mozts2005** [comment] 2015-07-14 00:10
Looks like there is a way. I will make sure that the Client can do this.  if not I will add this issue to our road map.  

https://developer.zendesk.com/rest_api/docs/core/users#update-user

**Comment by mozts2005** [comment] 2015-08-20 03:25
Will need to add org memberships to the client 
https://developer.zendesk.com/rest_api/docs/core/organization_memberships#delete-membership

**Comment by mozts2005** [comment] 2015-08-20 03:42
this is a duplicate of #124 CLOSING

**Closed by mozts2005** 2015-08-20 03:42 UTC
Labels: enhancement
