### ISSUE TITLE
Question re GetByPageUrl in incremental ticket export 

### ISSUE THREAD

**Issue by DCJackson** [mozts2005/ZendeskApi_v2#121] opened 2015-01-21 16:14 UTC
Hello,
GetByPageUrl  is working well for me getting view data (GroupTicketResponse). I am also using it to get all tickets in the incremental export (TicketExportResponse).

It is here that I randomly receive "Object reference not set to an instance of an object" on my GetByPageUrl call. So, I've been hyper-vigilant about checking for nulls everywhere, but it still occurs.

Code:

            var initialResponse = api.Tickets.GetInrementalTicketExport(startDate);

            int totalFetched = 0;

            if (initialResponse != null)
            {
                if (initialResponse.Results != null)
                {
                    eventLog.WriteEntry("Number of tickets in first call to incremental export: " + initialResponse.Results.Count());
                    totalFetched = initialResponse.Results.Count();

                    responseList.Add(initialResponse);
                    var nextPage = initialResponse.NextPage;

                    if (initialResponse.Results.Count() >= 1000)
                    {
                        TicketExportResponse paginationResponse = new TicketExportResponse();

                        do
                        {
                            //sleep 
                            System.Threading.Thread.Sleep(1000 * 65); // 65 seconds (This is necessary as this API call is rate limited)

                            if (!string.IsNullOrEmpty(nextPage))
                            {
                                paginationResponse = api.Tickets.GetByPageUrl<TicketExportResponse>(nextPage.Trim()); //**exception occurs here**
                                if (paginationResponse != null && !string.IsNullOrEmpty(paginationResponse.NextPage))
                                {
                                    nextPage = paginationResponse.NextPage;
                                }
                            }

                            if (paginationResponse != null && paginationResponse.Results != null)
                            {
                                totalFetched = totalFetched + paginationResponse.Results.Count();
                                eventLog.WriteEntry("Just fetched another " + paginationResponse.Results.Count() + " records. Total so far: " + totalFetched);
                                responseList.Add(paginationResponse);
                            }

                        } while (paginationResponse != null && paginationResponse.Results != null && paginationResponse.Results.Count >= 1000);
                    }
                }
            }

Am I missing something or is there a known issue? It pulls tickets great in batches of 1000 but...every now and again I get the Object Reference exception. It's random.

(I also sometimes get a 502 Bad Gateway and have put in re-try logic for that)

Thanks a lot in advance. Great API you created!
-DCJ

**Comment by mozts2005** [comment] 2015-07-13 23:41
Can you please send us a test case for this?

**Comment by mozts2005** [comment] 2015-08-20 03:52
I am unable to reproduce this issue until we have it in reproduce-able test case I am closing the issue

**Closed by mozts2005** 2015-08-20 03:52 UTC
Labels: Test case needed
