### ISSUE TITLE
Issue with Tickets.GetAuditsAsync()

### ISSUE THREAD

**Issue by ytwytw** [mozts2005/ZendeskApi_v2#335] opened 2018-05-31 14:54 UTC
If the zendesk ticket reply contains a url that has dash in it, the method throw exceptions

URL like this
https://www.ecreativeim.com/blog/index.php/2011/03/30/seo-basics-hyphen-or-underscore-for-seo-urls

**Comment by mozts2005** [comment] 2018-06-22 21:11
I am sure I am missing something. I am unable to reproduce this issue can you please Create a pull request with a failing test case?

**Comment by rwjdk** [comment] 2018-06-23 15:40
Also unable to reproduce - Tested with https://csharpapi.zendesk.com/agent/tickets/1436 ... 

![image](https://user-images.githubusercontent.com/7032102/41811237-33eeb20e-770c-11e8-9caa-946370dae6a5.png)

The call works as expected:
![image](https://user-images.githubusercontent.com/7032102/41811247-6bc66050-770c-11e8-9c2d-e82cc85d1932.png)

**Comment by mozts2005** [comment] 2018-06-23 15:55
Given now that two of us have not been able to reproduce this issue. I am going to close this issue. 

If you are still having issues please reopen and we can try and help you. 

@rwjdk  Thanks for the nice and clean reproduction steps.

**Closed by mozts2005** 2018-06-23 15:55 UTC
Labels: Bug, More Info Needed
